# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s.split()

['Hi', 'there', 'Sam!']

## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
dia = "The diameter of {planet} is {diameter} kilometers."
print(dia.format(planet="Earth",diameter = 12742))

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d["k1"][3]["tricky"][3]["target"][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [ ]:
a = []
for i in range(0,10):
  a.append(0)
print(a)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [ ]:
arz=np.zeros(10)
print(arz)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
a = []
for i in range(0,10):
  a.append(5)
print(a)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


In [ ]:
ar5=np.ones(10)*5
print(ar5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [ ]:
b = []
for i in range (20,36):
  if i%2 == 0:
    b.append(i)
  else:
    pass
print(b)

[20, 22, 24, 26, 28, 30, 32, 34]


In [ ]:
even=np.arange(20,36,2)
print(even)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
import numpy as np
mat = np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
con = np.concatenate((a,b),axis=0)
print(con)

[1 2 3 4 5 6]


## Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [ ]:
south_india = {"State":["Andhra Pradesh","Karnataka","Tamilnadu"],"Capital":["Amaravati","Bengaluru","Chennai"]}
pd.DataFrame(south_india)

State    Capital
0  Andhra Pradesh  Amaravati
1       Karnataka  Bengaluru
2       Tamilnadu    Chennai

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
a = "{date1} Jan,2023"
b = "{date2} Feb,2023"
c =[]
for i in range (1,32):
  c.append(a.format(date1=i))
for j in range (1,11):
  c.append(b.format(date2=j))

pd.DataFrame(c)

0
0    1 Jan,2023
1    2 Jan,2023
2    3 Jan,2023
3    4 Jan,2023
4    5 Jan,2023
5    6 Jan,2023
6    7 Jan,2023
7    8 Jan,2023
8    9 Jan,2023
9   10 Jan,2023
10  11 Jan,2023
11  12 Jan,2023
12  13 Jan,2023
13  14 Jan,2023
14  15 Jan,2023
15  16 Jan,2023
16  17 Jan,2023
17  18 Jan,2023
18  19 Jan,2023
19  20 Jan,2023
20  21 Jan,2023
21  22 Jan,2023
22  23 Jan,2023
23  24 Jan,2023
24  25 Jan,2023
25  26 Jan,2023
26  27 Jan,2023
27  28 Jan,2023
28  29 Jan,2023
29  30 Jan,2023
30  31 Jan,2023
31   1 Feb,2023
32   2 Feb,2023
33   3 Feb,2023
34   4 Feb,2023
35   5 Feb,2023
36   6 Feb,2023
37   7 Feb,2023
38   8 Feb,2023
39   9 Feb,2023
40  10 Feb,2023

# ***date series: Using pd.data_range***

In [ ]:
c = pd.date_range("2023-01-01","2023-02-10")
pd.DataFrame(c)

0
0  2023-01-01
1  2023-01-02
2  2023-01-03
3  2023-01-04
4  2023-01-05
5  2023-01-06
6  2023-01-07
7  2023-01-08
8  2023-01-09
9  2023-01-10
10 2023-01-11
11 2023-01-12
12 2023-01-13
13 2023-01-14
14 2023-01-15
15 2023-01-16
16 2023-01-17
17 2023-01-18
18 2023-01-19
19 2023-01-20
20 2023-01-21
21 2023-01-22
22 2023-01-23
23 2023-01-24
24 2023-01-25
25 2023-01-26
26 2023-01-27
27 2023-01-28
28 2023-01-29
29 2023-01-30
30 2023-01-31
31 2023-02-01
32 2023-02-02
33 2023-02-03
34 2023-02-04
35 2023-02-05
36 2023-02-06
37 2023-02-07
38 2023-02-08
39 2023-02-09
40 2023-02-10

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24